apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deconz-data
  namespace: deconz
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
