apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwavejs-data
  namespace: zwavejs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
