apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 5m
  targetNamespace: zigbee2mqtt
  chart:
    spec:
      chart: zigbee2mqtt
      version: 2.7.1
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: zigbee2mqtt
      interval: 10m
  values:
    fullnameOverride: zigbee2mqtt
    nodeSelector:
      kubernetes.io/hostname: harmen-rpi-ssd

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: zigbee2mqtt.home.lan
          paths:  
            - path: /
              pathType: Prefix
            - path: /api/
              pathType: Prefix
    
    zigbee2mqtt:
      mqtt:
        server: "mqtt://mosquitto.home.lan:1883"
      serial:
        port: "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2456829-if00"
    
    
