apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
      version: "0.3.36"
  values:
    env:
      - name: TZ
        value: Europe/Amsterdam

    service:
      main:
        type: ClusterIP
        ports:
          http:
            port: 8123

    ingress:
      enabled: true
      labels: {}
      annotations: {}
      hosts:
        - host: homeassistant.home.lan
          paths:
            - path: /
              pathType: ImplementationSpecific

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: local-path
