apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
      version: "0.3.36"
  values:
    env:
      - name: TZ
        value: Europe/Amsterdam

    service:
      port: 8123
    
    hostNetwork: true

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: homeassistant.home.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []

    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.42.0.0/16 # k3s pod CIDR (Traefik pod IPs)
        - 127.0.0.1/32

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: local-path
