apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
      version: "0.3.36"
  values:
    fullnameOverride: apps-homeassistant

    # use type deployment and recreate, 
    # because volume with local-path can only handle RWO
    controller:
      type: Deployment
    deploymentStrategy: Recreate
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    podSecurityContext: {}
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
      seccompProfile:
        type: RuntimeDefault

    env:
      - name: TZ
        value: Europe/Amsterdam

    service:
      port: 8123
    
    hostNetwork: true

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: homeassistant.home.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # add configuration-files as configmap and overwrite
    additionalVolumes:
      - name: ha-config-src
        configMap:
          name: ha-config
    initContainers:
      - name: seed-config
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            cp -a /config-src/. /config/
            chown -R 1000:1000 /config
        volumeMounts:
          - name: ha-config-src
            mountPath: /config-src
          - name: apps-homeassistant-pvc
            mountPath: /config
      - name: sync-solaredge-custom-components
        image: alpine/git:2.45.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            dest="/config/custom_components/solaredge_modbus"
            tmpdir="$(mktemp -d)"
            git clone --depth 1 https://github.com/binsentsu/home-assistant-solaredge-modbus.git "$tmpdir"
            mkdir -p /config/custom_components
            rm -rf "$dest"
            cp -a "$tmpdir/custom_components/solaredge_modbus" "$dest"
            chown -R 1000:1000 /config/custom_components
        volumeMounts:
          - name: apps-homeassistant-pvc
            mountPath: /config

    persistence:
      enabled: true
      existingClaim: apps-homeassistant-pvc-config
