apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
      version: "0.3.36"
  values:
    fullnameOverride: apps-homeassistant

    podSecurityContext:
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false

    env:
      - name: TZ
        value: Europe/Amsterdam

    service:
      port: 8123
    
    hostNetwork: true

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: homeassistant.home.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # add configuration-files as configmap and overwrite
    additionalVolumes:
      - name: ha-config-src
        configMap:
          name: ha-config
    initContainers:
      - name: seed-config
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            cp -a /config-src/. /config/
            chown -R 1000:1000 /config
        volumeMounts:
          - name: ha-config-src
            mountPath: /config-src
          - name: apps-homeassistant-pv-config
            mountPath: /config

    persistence:
      enabled: true
      existingVolume: apps-homeassistant-pv-config
