apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 10m
  chart:
    spec:
      chart: home-assistant
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: homeassistant
      version: "0.3.36"
  values:
    fullnameOverride: apps-homeassistant

    # use type deployment and recreate, 
    # because volume with local-path can only handle RWO
    controller:
      type: Deployment
    deploymentStrategy: Recreate
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    podSecurityContext: {}
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsNonRoot: false
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
      seccompProfile:
        type: RuntimeDefault

    env:
      - name: TZ
        value: Europe/Amsterdam

    service:
      port: 8123
    
    hostNetwork: true

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: homeassistant.home.lan
          paths:
            - path: /
              pathType: Prefix
      tls: []

    # add configuration-files as configmap and overwrite
    additionalVolumes:
      - name: ha-config-src
        configMap:
          name: ha-config
      - name: ha-blueprints-automation-src
        configMap:
          name: ha-blueprints-automation
      - name: ha-automation-dimmers-src
        configMap:
          name: ha-automation-dimmers
      - name: ha-automation-motion-src
        configMap:
          name: ha-automation-motion
      - name: ha-automation-lights-src
        configMap:
          name: ha-automation-lights
      - name: ha-helpers-src
        configMap:
          name: ha-helpers
    initContainers:
      - name: seed-config
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e

            # copy config files from configmap to /config
            cp -a /config-src/. /config/

            # copy blueprints from configmap to /config/blueprints/
            mkdir -p /config/blueprints/automation
            cp -a /blueprints-automation-src/. /config/blueprints/automation/
            find /config/blueprints -type f -maxdepth 2

            # copy automations from configmap to /config/automations
            mkdir -p /config/automation/dimmers
            cp -a /automation-dimmers-src/. /config/automation/dimmers/
            mkdir -p /config/automation/motion
            cp -a /automation-motion-src/. /config/automation/motion/
            mkdir -p /config/automation/lights
            cp -a /automation-lights-src/. /config/automation/lights/
            find /config/automation -type f -maxdepth 2

            # copy helpers from configmap to /config/helpers
            mkdir -p /config/helpers
            cp -a /helpers-src/. /config/helpers/
            find /config/helpers -type f -maxdepth 2

            # set correct ownership
            chown -R 1000:1000 /config
        volumeMounts:
          - name: ha-config-src
            mountPath: /config-src
          - name: ha-blueprints-automation-src
            mountPath: /blueprints-automation-src
          - name: ha-automation-dimmers-src
            mountPath: /automation-dimmers-src
          - name: ha-automation-motion-src
            mountPath: /automation-motion-src
          - name: ha-automation-lights-src
            mountPath: /automation-lights-src
          - name: ha-helpers-src
            mountPath: /helpers-src
          - name: apps-homeassistant-pvc
            mountPath: /config
      - name: sync-solaredge-custom-components
        image: alpine/git:2.45.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            dest="/config/custom_components/solaredge_modbus"
            tmpdir="$(mktemp -d)"
            git clone --depth 1 https://github.com/binsentsu/home-assistant-solaredge-modbus.git "$tmpdir"
            mkdir -p /config/custom_components
            rm -rf "$dest"
            cp -a "$tmpdir/custom_components/solaredge_modbus" "$dest"
            chown -R 1000:1000 /config/custom_components
        volumeMounts:
          - name: apps-homeassistant-pvc
            mountPath: /config

    persistence:
      enabled: true
      existingClaim: apps-homeassistant-pvc-config
