apiVersion: batch/v1
kind: Job
metadata:
  name: ha-onboarding
  namespace: homeassistant
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: onboard
          image: alpine:latest
          command: ["/bin/sh","-lc"]
          env:
            - name: HA_URL
              value: "http://apps-homeassistant.homeassistant.svc.cluster.local:8123"
            - name: HA_NAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: name
            - name: HA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: username
            - name: HA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: password
            - name: HA_LANGUAGE
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: language
            - name: HA_CLIENT_ID
              value: "http://homeassistant.home.lan"
          args:
            - |
              set -euo pipefail

              echo "Installing curl + jq…"
              apk add --no-cache curl jq

              ONBOARDING_URL="$HA_URL/api/onboarding"

              echo "Waiting for HA onboarding endpoint…"
              until curl -s "$ONBOARDING_URL" | jq . >/dev/null 2>&1; do
                echo "   not available yet, retrying in 3s…"
                sleep 3
              done

              echo "Onboarding state:"
              curl -s "$ONBOARDING_URL" | jq .

              user_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="user") | .done')"
              core_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="core_config") | .done')"

              echo "user_done=$user_done"
              echo "core_done=$core_done"

              if [ "$user_done" = "true" ] && [ "$core_done" = "true" ]; then
                echo "User + core_config already done → exiting"
                exit 0
              fi

              if [ "$user_done" != "true" ]; then
                echo "Creating initial Home Assistant user…"

                create_code="$(curl -s -o /tmp/ha_create.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/users" \
                  -H "Content-Type: application/json" \
                  -d "$(jq -n \
                        --arg name "$HA_NAME" \
                        --arg username "$HA_USERNAME" \
                        --arg password "$HA_PASSWORD" \
                        --arg client_id "$HA_CLIENT_ID" \
                        --arg language "$HA_LANGUAGE" \
                        '{name:$name, username:$username, password:$password, client_id:$client_id, language:$language}')" )"

                echo "POST /api/onboarding/users HTTP=$create_code"
                cat /tmp/ha_create.json || true

                if [ "$create_code" != "200" ]; then
                  echo "User creation failed"
                  exit 1
                fi

                AUTH_CODE="$(jq -r '.auth_code // empty' /tmp/ha_create.json)"
                if [ -z "$AUTH_CODE" ]; then
                  echo "Missing auth_code in response"
                  exit 1
                fi

                echo "User created successfully"
              else
                echo "User step already done; cannot mint token via onboarding/users anymore."
                echo "If core_config is still false, you'll need an existing long-lived token to call /api/onboarding/core_config."
                exit 1
              fi

              echo "Exchanging auth_code for access token…"
              token_code="$(curl -s -o /tmp/ha_token.json -w "%{http_code}" \
                -X POST "$HA_URL/auth/token" \
                -H "Content-Type: application/x-www-form-urlencoded" \
                --data-urlencode "grant_type=authorization_code" \
                --data-urlencode "code=$AUTH_CODE" \
                --data-urlencode "client_id=$HA_CLIENT_ID")"

              echo "POST /auth/token HTTP=$token_code"
              cat /tmp/ha_token.json || true

              if [ "$token_code" != "200" ]; then
                echo "Token exchange failed"
                exit 1
              fi

              ACCESS_TOKEN="$(jq -r '.access_token // empty' /tmp/ha_token.json)"
              if [ -z "$ACCESS_TOKEN" ]; then
                echo "Missing access_token in token response"
                exit 1
              fi

              if [ "$core_done" != "true" ]; then
                echo "Marking core_config as done…"
                core_code="$(curl -s -o /tmp/ha_core.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/core_config" \
                  -H "Authorization: Bearer $ACCESS_TOKEN")"

                echo "POST /api/onboarding/core_config HTTP=$core_code"
                cat /tmp/ha_core.json || true

                if [ "$core_code" != "200" ]; then
                  echo "core_config step failed"
                  exit 1
                fi

                echo "core_config marked done"
              else
                echo "core_config already done"
              fi

              echo "Final onboarding state:"
              curl -s "$ONBOARDING_URL" | jq .
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-onboarding-admin
  namespace: homeassistant
type: Opaque
stringData:
  name: "Home Assistant Administrator"
  username: admin
  password: admin
  language: "nl"