apiVersion: batch/v1
kind: Job
metadata:
  name: ha-onboarding
  namespace: homeassistant
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: onboard
          image: alpine:latest
          command: ["/bin/sh","-lc"]
          env:
            - name: HA_URL
              value: "http://apps-homeassistant.homeassistant.svc.cluster.local:8123"
            - name: HA_NAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: name
            - name: HA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: username
            - name: HA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: password
            - name: HA_LANGUAGE
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: language
            - name: HA_CLIENT_ID
              value: "http://homeassistant.home.lan"
          args:
            - |
              set -euo pipefail

              echo "Installing curl + jq…"
              apk add --no-cache curl jq

              ONBOARDING_URL="$HA_URL/api/onboarding"

              echo "Waiting for HA onboarding endpoint…"
              until curl -s "$ONBOARDING_URL" | jq . >/dev/null 2>&1; do
                echo "   not available yet, retrying in 3s…"
                sleep 3
              done

              echo "Onboarding state:"
              curl -s "$ONBOARDING_URL" | jq .

              user_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="user") | .done')"
              core_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="core_config") | .done')"
              analytics_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="analytics") | .done')"
              integration_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="integration") | .done')"

              echo "user_done=$user_done"
              echo "core_done=$core_done"
              echo "analytics_done=$analytics_done"
              echo "integration_done=$integration_done"

              ACCESS_TOKEN=""

              if [ "$user_done" != "true" ]; then
                echo "Creating initial Home Assistant user…"

                create_code="$(curl -s -o /tmp/ha_create.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/users" \
                  -H "Content-Type: application/json" \
                  -d "$(jq -n \
                        --arg name "$HA_NAME" \
                        --arg username "$HA_USERNAME" \
                        --arg password "$HA_PASSWORD" \
                        --arg client_id "$HA_CLIENT_ID" \
                        --arg language "$HA_LANGUAGE" \
                        '{name:$name, username:$username, password:$password, client_id:$client_id, language:$language}')" )"

                echo "POST /api/onboarding/users HTTP=$create_code"
                cat /tmp/ha_create.json || true

                if [ "$create_code" != "200" ]; then
                  echo "User creation failed"
                  exit 1
                fi

                AUTH_CODE="$(jq -r '.auth_code // empty' /tmp/ha_create.json)"
                if [ -z "$AUTH_CODE" ]; then
                  echo "Missing auth_code in response"
                  exit 1
                fi

                echo "User created successfully"
              else
                echo "User step already done; cannot mint token via onboarding/users anymore."
              fi

              if [ -z "$ACCESS_TOKEN" ] && [ -n "${AUTH_CODE:-}" ]; then
                echo "Exchanging auth_code for access token…"
                token_code="$(curl -s -o /tmp/ha_token.json -w "%{http_code}" \
                  -X POST "$HA_URL/auth/token" \
                  -H "Content-Type: application/x-www-form-urlencoded" \
                  --data-urlencode "grant_type=authorization_code" \
                  --data-urlencode "code=$AUTH_CODE" \
                  --data-urlencode "client_id=$HA_CLIENT_ID")"

                echo "POST /auth/token HTTP=$token_code"
                cat /tmp/ha_token.json || true

                if [ "$token_code" != "200" ]; then
                  echo "Token exchange failed"
                  exit 1
                fi

                ACCESS_TOKEN="$(jq -r '.access_token // empty' /tmp/ha_token.json)"
                if [ -z "$ACCESS_TOKEN" ]; then
                  echo "Missing access_token in token response"
                  exit 1
                fi
              fi

              if [ "$core_done" != "true" ] && [ -n "$ACCESS_TOKEN" ]; then
                echo "Marking core_config as done…"
                core_code="$(curl -s -o /tmp/ha_core.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/core_config" \
                  -H "Authorization: Bearer $ACCESS_TOKEN")"

                echo "POST /api/onboarding/core_config HTTP=$core_code"
                cat /tmp/ha_core.json || true

                if [ "$core_code" != "200" ]; then
                  echo "core_config step failed"
                  exit 1
                fi

                echo "core_config marked done"
              elif [ "$core_done" = "true" ]; then
                echo "core_config already done"
              else
                echo "core_config pending but no access token available; skipping"
              fi

              if [ "$analytics_done" != "true" ] && [ -n "$ACCESS_TOKEN" ]; then
                echo "Opting out of analytics…"
                analytics_code="$(curl -s -o /tmp/ha_analytics.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/analytics" \
                  -H "Authorization: Bearer $ACCESS_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d '{"preferences":{"base":false,"diagnostics":false,"usage":false}}')"

                echo "POST /api/onboarding/analytics HTTP=$analytics_code"
                cat /tmp/ha_analytics.json || true

                if [ "$analytics_code" != "200" ]; then
                  echo "analytics step failed"
                  exit 1
                fi

                echo "analytics opt-out recorded"
              elif [ "$analytics_done" = "true" ]; then
                echo "analytics already done"
              else
                echo "analytics pending but no access token available; skipping"
              fi

              if [ "$integration_done" != "true" ] && [ -n "$ACCESS_TOKEN" ]; then
                echo "Completing integration step…"
                integration_code="$(curl -s -o /tmp/ha_integration.json -w "%{http_code}" \
                  -X POST "$HA_URL/api/onboarding/integration" \
                  -H "Authorization: Bearer $ACCESS_TOKEN" \
                  -H "Content-Type: application/json" \
                  -d "$(jq -n --arg client_id "$HA_CLIENT_ID" --arg redirect_uri "$HA_CLIENT_ID" '{client_id:$client_id, redirect_uri:$redirect_uri}')")"

                echo "POST /api/onboarding/integration HTTP=$integration_code"
                cat /tmp/ha_integration.json || true

                if [ "$integration_code" != "200" ]; then
                  echo "integration step failed"
                  exit 1
                fi

                echo "integration step completed"
              elif [ "$integration_done" = "true" ]; then
                echo "integration already done"
              else
                echo "integration pending but no access token available; skipping"
              fi

              echo "Final onboarding state:"
              curl -s "$ONBOARDING_URL" | jq .
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-onboarding-admin
  namespace: homeassistant
type: Opaque
stringData:
  name: "Home Assistant Administrator"
  username: admin
  password: admin
  language: "nl"
