apiVersion: batch/v1
kind: Job
metadata:
  name: ha-onboarding
  namespace: homeassistant
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: onboard
          image: curlimages/curl:8.10.1
          env:
            - name: HA_URL
              value: "http://apps-homeassistant.homeassistant.svc.cluster.local:8123"
            - name: HA_NAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: name
            - name: HA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: username
            - name: HA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ha-onboarding-admin
                  key: password
          command: ["/bin/sh","-lc"]
          args:
            - |
              set -euo pipefail
              
              ONBOARDING_URL="$HA_URL/api/onboarding"

              echo "Waiting for HA onboarding endpoint…"
              until curl -s "$ONBOARDING_URL" | jq . >/dev/null 2>&1; do
                sleep 3
              done

              echo "Onboarding state:"
              curl -s "$ONBOARDING_URL" | jq .

              # Check if user step is already done
              user_done="$(curl -s "$ONBOARDING_URL" | jq -r '.[] | select(.step=="user") | .done')"

              echo "user_done=$user_done"

              if [ "$user_done" = "true" ]; then
                echo "User already created → exiting"
                exit 0
              fi

              echo "Creating initial Home Assistant user…"

              create_code="$(curl -s -o /tmp/ha_create.json -w "%{http_code}" \
                -X POST "$HA_URL/api/onboarding/users" \
                -H "Content-Type: application/json" \
                -d "$(jq -n \
                      --arg name "$HA_NAME" \
                      --arg username "$HA_USERNAME" \
                      --arg password "$HA_PASSWORD" \
                      '{name:$name, username:$username, password:$password}')")"

              echo "POST /api/onboarding/users HTTP=$create_code"
              cat /tmp/ha_create.json || true

              if [ "$create_code" != "200" ]; then
                echo "User creation failed"
                exit 1
              fi

              echo "User created successfully"
---
apiVersion: v1
kind: Secret
metadata:
  name: ha-onboarding-admin
  namespace: homeassistant
type: Opaque
stringData:
  name: "Home Assistant Administrator"
  username: admin
  password: admin