apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: homeassistant
  name: apps-homeassistant-pv-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
