apiVersion: v1
kind: PersistentVolume
metadata:
  name: apps-homeassistant-pv-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-path"
  volumeMode: Filesystem