apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-homeassistant-pvc
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: apps-homeassistant-pv-config
