apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apps-homeassistant-pvc-config
  namespace: homeassistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
